version: "3.4"
services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    stdin_open: true
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    stdin_open: true
  client_vscode:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client_vscode
    stdin_open: true
