package(default_visibility = ["//visibility:public"])

py_test(
    name = "number_tests",
    srcs = [
        ":number_test.py",
    ],
    main = ":number_test.py",
)

py_test(
    name = "string_tests",
    srcs = [
        ":string_test.py",
    ],
    main = ":string_test.py",
)