package(default_visibility = ["//visibility:public"])

py_library(
    name = "package",
    srcs = [
        "a.py",
        "b.py",
        "nested/files/c.py",
        ":nested/files/d.py",
    ],
    deps = [

    ],
)
