# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Server Java CI with Gradle

on:
  push:
    branches: [ checkstyle, develop ]
  pull_request:
    branches: [ checkstyle, develop ]
  

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew and build
      run: |
        cd server
        chmod +x gradlew
        ./gradlew build
        gradle test
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.3.1
      with:
        workdir: ./server
        checkstyle_config: ./server/bazel_checks.xml
        fail_on_error: true
        filter_mode: nofilter
        level: error

        
